# Generated by Django 5.1.3 on 2024-12-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_session_id_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
